In [1]:
import numpy as np

# 1차원 배열 초기화 
a = np.arange( 6 )
b = np.arange( 2, 6 )
c = np.arange( 1, 6, 2 )
d = np.linspace( 0, 0.5, 6 )

# 배열 값 출력
print( a )
print( b )
print( c )
print( d )

[0 1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[0.  0.1 0.2 0.3 0.4 0.5]
