In [2]:
import numpy as np 

# 3x2 행렬, 0에서 10미만 임의의 정수 값으로 균일분포 초기화
a = np.random.randint( 0, 10, (3, 2) )
print( "np.random.randint( 0, 10, (3, 2) )", a, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수 값으로 균일분포 초기화
b = np.random.rand(3,2) 
print( "np.random.rand( (3, 2) )", b, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수 값으로 균일분포 초기화
c = np.random.uniform(1, 10, (3,2) ) 
print( "np.random.uniform(1, 10, (3,2) )", c, sep="\n" )
print( "-"*40 ) 

np.random.randint( 0, 10, (3, 2) )
[[2 4]
 [2 3]
 [4 3]]
----------------------------------------
np.random.rand( (3, 2) )
[[0.63574768 0.16817645]
 [0.29532108 0.28020971]
 [0.83887844 0.09292967]]
----------------------------------------
np.random.uniform(1, 10, (3,2) )
[[4.36805441 1.44862442]
 [1.98017424 2.00436157]
 [2.51648255 5.66585109]]
----------------------------------------
