In [1]:
import numpy as np 

# 3x2 행렬, 0에서 10미만 임의의 정수값으로 균일분포 초기화
a = np.random.randint( 0, 10, (3, 2) )
print( "np.random.randint( 0, 10, (3, 2) )", a, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수값으로 균일분포 초기화
b = np.random.rand(3,2) 
print( "np.random.rand( (3, 2) )", b, sep="\n" )
print( "-"*40 )

# 3x2 행렬, 0에서 1미만 임의의 실수값으로 균일분포 초기화
c = np.random.uniform(1, 10, (3,2) ) 
print( "np.random.uniform(1, 10, (3,2) )", c, sep="\n" )
print( "-"*40 ) 

np.random.randint( 0, 10, (3, 2) )
[[6 1]
 [6 3]
 [6 7]]
----------------------------------------
np.random.rand( (3, 2) )
[[0.59325727 0.99943817]
 [0.90752831 0.92822112]
 [0.76673498 0.15847999]]
----------------------------------------
np.random.uniform(1, 10, (3,2) )
[[1.3184268  4.82479701]
 [1.26138308 3.61981298]
 [7.31282225 6.33596172]]
----------------------------------------
