In [16]:
import numpy as np

a = np.random.randint( 0, 10, (3, 4) )

print( "a =", a, sep="\n" )
print( "a.shape =", a.shape )
print( "a.ravel() =", a.ravel() )
print( "a.ravel().shape =", a.ravel().shape )
print( "a.reshape(2, 6) =", a.reshape(2, 6), sep="\n" )
print( "a.T =", a.T )
print( "a.T.shape =", a.T.shape )

a =
[[6 4 6 1]
 [0 0 6 1]
 [3 9 2 7]]
a.shape = (3, 4)
a.ravel() = [6 4 6 1 0 0 6 1 3 9 2 7]
a.ravel().shape = (12,)
a.reshape(2, 6) =
[[6 4 6 1 0 0]
 [6 1 3 9 2 7]]
a.T = [[6 0 3]
 [4 0 9]
 [6 6 2]
 [1 1 7]]
a.T.shape = (4, 3)
