In [1]:
import numpy as np

# Matlab 코딩 스타일
i, j = np.arange(2), np.arange(3)
i, j = np.meshgrid( i, j, indexing="ij" )
a = j - i 

print( "i = ", i, "-"*40, sep="\n")
print( "j = ", j, "-"*40, sep="\n")
print( "a = j - i", a, "-"*40, sep="\n") 

i = 
[[0 0 0]
 [1 1 1]]
----------------------------------------
j = 
[[0 1 2]
 [0 1 2]]
----------------------------------------
a = j - i
[[ 0  1  2]
 [-1  0  1]]
----------------------------------------


In [6]:
import numpy as np

a = np.arange( 1, 5 ).reshape( -1, 2 )

I, J = np.indices( a.shape )

b = a[ I, J ]
c = a[ J, I ]

print( "a = ", a, "*"*40, sep="\n" )
print( "I = ", I, "*"*40, sep="\n" )
print( "J = ", J, "*"*40, sep="\n" )
print( "b = ", b, "*"*40, sep="\n" )
print( "c = ", c, "*"*40, sep="\n" )

a = 
[[1 2]
 [3 4]]
****************************************
I = 
[[0 0]
 [1 1]]
****************************************
J = 
[[0 1]
 [0 1]]
****************************************
b = 
[[1 2]
 [3 4]]
****************************************
c = 
[[1 3]
 [2 4]]
****************************************
