In [12]:
import numpy as np

a = np.array( [7, 4, 6, 5] )
b = np.argsort( a )
c = a[ b ]

print( 'a = ', a )
print( 'b = ', b )
print( 'c = ', c )

a = np.array( [ [7, 2, 9], [4, 3, 8],
               [6, 1, 7], [5, 0,4] ] 
             )
b = np.argsort( a[:, 0] )
c = a[ b ]
print( 'a = ', a, sep='\n' )
print( 'b = ', b )
print( 'c = ', c, sep='\n' )

a =  [7 4 6 5]
b =  [1 3 2 0]
c =  [4 5 6 7]
a = 
[[7 2 9]
 [4 3 8]
 [6 1 7]
 [5 0 4]]
b =  [1 3 2 0]
c = 
[[4 3 8]
 [5 0 4]
 [6 1 7]
 [7 2 9]]
