In [4]:
import numpy as np

a = np.array( [ [1,5], [2, 7], [2, 6 ], [3, 4] ] )
aa = np.argsort( a[:,1] )
b = a[ aa ]
c = b[ np.argsort( b[:,0], kind='stable' ) ]

print( 'a = ', a , sep='\n' )
print( 'aa = ', aa , sep='\n' )
print( 'b = ', b , sep='\n' )
print( 'c = ', c , sep='\n' )

a = 
[[1 5]
 [2 7]
 [2 6]
 [3 4]]
aa = 
[3 0 2 1]
b = 
[[3 4]
 [1 5]
 [2 6]
 [2 7]]
c = 
[[1 5]
 [2 6]
 [2 7]
 [3 4]]
