In [5]:
import numpy as np

a = np.array( [ [3,4], [2, 7], [1, 5], [2, 6] ] )
b = np.rot90(a)
c = np.lexsort( b )
d = a[c]

print( 'a = ', a , sep='\n' )
print( 'b = ', b , sep='\n' )
print( 'c = ', c , )
print( 'd = ', d , sep='\n' )

a = 
[[3 4]
 [2 7]
 [1 5]
 [2 6]]
b = 
[[4 7 5 6]
 [3 2 1 2]]
c =  [2 3 1 0]
d = 
[[1 5]
 [2 6]
 [2 7]
 [3 4]]
