In [4]:
import numpy as np

a = np.random.rand( 3, 4, 5 )

print( "a = ", a, sep="\n" )
print( "-"*60  ) 
print( "a.shape = ", a.shape )


a = 
[[[0.23796271 0.31994786 0.19027731 0.58072393 0.29623469]
  [0.42910864 0.57867705 0.19814339 0.42957149 0.74364069]
  [0.55160963 0.95754807 0.65785352 0.62088809 0.71064785]
  [0.11758377 0.89423157 0.85095458 0.18281941 0.7505835 ]]

 [[0.35480457 0.74710912 0.17827974 0.46080992 0.25401952]
  [0.38152094 0.04178414 0.2701933  0.79466661 0.28923642]
  [0.22827391 0.38745911 0.55507314 0.09498382 0.4166184 ]
  [0.73283189 0.80409366 0.3103314  0.31850185 0.28527592]]

 [[0.43894745 0.58065577 0.73441951 0.78152762 0.99985883]
  [0.5350796  0.52698092 0.65663022 0.85754635 0.33449348]
  [0.59862036 0.41168399 0.24392059 0.3229884  0.06596546]
  [0.79550156 0.90341248 0.45999738 0.31912154 0.58464032]]]
------------------------------------------------------------
a.shape =  (3, 4, 5)
