In [26]:
import numpy as np

def f(y, x):
   return 10*y + x

b = np.fromfunction(f, (5, 4), dtype=int)

print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [3]:
import numpy as np

a = np.array( [1,2,3,4,5,6,7,6,5,4,3,2,1] )
b = a > 5 # 5 초과 여부 판별 배열 
print( a, b, "*"*40, sep='\n' ) 
c = np.where( a > 5 )  # 5초과 데이터들의 인덱스 배열
d = np.nonzero( a > 5 ) # 5초과 데이터들의 인덱스 배열 
print( c, d, "*"*40, sep='\n' ) 

# 5 미만은 0으로, 5 이상은 1 로 설정 
a[ a < 5 ] = 0; a[ a >= 5 ] = 1
a = np.array( [1,2,3,4,5,6,7,6,5,4,3,2,1] )
e = np.where( a >= 5, 1, 0 )
print( a, e, "*"*40, sep='\n' )

print( a )
# 3 미만은 3으로, 5초과는 5로 설정
a[ a < 3 ] = 3; a[ a > 5 ] = 5
print( a )
a = np.array( [1,2,3,4,5,6,7,6,5,4,3,2,1] )
f = np.clip(a, 3, 5 )
print( f )

[1 2 3 4 5 6 7 6 5 4 3 2 1]
[False False False False False  True  True  True False False False False
 False]
****************************************
(array([5, 6, 7], dtype=int64),)
(array([5, 6, 7], dtype=int64),)
****************************************
[1 2 3 4 5 6 7 6 5 4 3 2 1]
[0 0 0 0 1 1 1 1 1 0 0 0 0]
****************************************
[1 2 3 4 5 6 7 6 5 4 3 2 1]
[3 3 3 4 5 5 5 5 5 4 3 3 3]
[3 3 3 4 5 5 5 5 5 4 3 3 3]


In [7]:
import numpy as np

a = np.array( [4, 8] )
b = np.array( [2, 5] )

print( a + b )
print( a - b )
print( a * b )
print( a / b )
print( a // b )
print( a ** b )

[ 6 13]
[2 3]
[ 8 40]
[2.  1.6]
[2 1]
[   16 32768]


In [10]:
import numpy as np

a = np.array( [2, 3] )

print( a ** 2 )
print( np.sqrt( [4, 9] ) )
print( np.exp( [1, 2] ) )
print( np.log( [np.e, np.e**2] ) )

[4 9]
[2. 3.]
[2.71828183 7.3890561 ]
[1. 2.]


In [14]:
import numpy as np

a = np.array( [1, 2] )
b = np.array( [3, 4] )

print( np.dot( a, b ) )
print( a @ b )

print( np.cross( [2, 0, 0], [0, 3, 0] ) )

11
11
[0 0 6]


In [15]:
import numpy as np

print( np.sin( [ np.pi, np.pi/2 ] ) )
print( np.arcsin( [ 0., 1. ] ) )

print( np.hypot( [3., 5.], [4., 12.] ) )

[1.2246468e-16 1.0000000e+00]
[0.         1.57079633]
[ 5. 13.]


In [16]:
import numpy as np

a = np.array( [ 1.1, 1.5, 1.9, 2.5 ] )
print( np.floor( a ) )
print( np.ceil( a ) )
print( np.round( a ) )

[1. 1. 1. 2.]
[2. 2. 2. 3.]
[1. 2. 2. 2.]


In [14]:
import numpy as np 

a = np.array( [ 1, 2, 3 ] )

print( a.max(), np.max( a ) )
print( a.argmax(), np.argmax( a ) )

print( "*"*40 )
print( a.min(), np.min( a ) )
print( a.argmin(), np.argmin( a ) ) 

print( "*"*40 )
print( a.sum(), np.sum( a ) )
print( a.mean(), np.mean( a ) )
print( a.var(), np.var( a ) )
print( a.std(), np.std( a ) )

3 3
2 2
****************************************
1 1
0 0
****************************************
6 6
2.0 2.0
0.6666666666666666 0.6666666666666666
0.816496580927726 0.816496580927726


In [18]:
a = [ 3, 2, 1]
a.sort()
print( a )

import numpy as np 
a = np.array( [ 3, 2, 1 ] )
np.sort( a )
print( a )
a.sort()
print( a )

[1, 2, 3]
[3 2 1]
[1 2 3]


In [28]:
import math

print( 0.1 + 0.2 == 0.3 )
print( np.allclose( 0.1 + 0.2, 0.3 ) )
print( math.isclose( 0.1 + 0.2 , 0.3) )

print( "*"*40 )
print( 1e-9 == 2e-9 )
print( np.allclose( 1e-9, 2e-9 ) )
print( math.isclose( 1e09, 2e-9 ) )

print( "*"*40 )
print( 0.1 + 0.2 - 0.3 == 0 )
print( np.allclose( 0.1 + 0.2-0.3, 0 ) )
print( math.isclose( 0.1 + 0.2 - 0.3, 0 ) )


False
True
True
****************************************
False
True
False
****************************************
False
True
False
