2차원 배열 행렬 예제입니다.

In [27]:
import numpy as np 

a = np.array( [ 1, 2, 3 ] )
b = np.array( [ 1, 2, 3 ] )

print( "a = ", a )
print( "b = ", b )

print( "a@b = ", a@b )
print( "inner = ", np.dot(a, b) )
print( "outer = ", np.outer(a, b) )

a =  [1 2 3]
b =  [1 2 3]
a@b =  14
inner =  14
outer =  [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [8]:
import numpy as np
a = np.array( [ [8, 0, 0, 6], [1, 4, 3, 0], [0, 3, 1, 9] ] )

print( "a = ", a ) 
print( "a address = ", a.data )

b = a.reshape( 3, -1 )
print( "b = ", b )
print( "b address ", b.data )

a.resize( 2, 6 )
print( "a = ", a )
print( "a address = ", a.data )

a =  [[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
a address =  <memory at 0x00000149F31E4A00>
b =  [[8 0 0 6]
 [1 4 3 0]
 [0 3 1 9]]
b address  <memory at 0x00000149F31E4A00>
a =  [[8 0 0 6 1 4]
 [3 0 0 3 1 9]]
a address =  <memory at 0x00000149F31E4A00>
