In [20]:
import numpy as np

a = np.arange( 1, 13 ).reshape( -1, 4 )
b = np.arange( 1, 9 ).reshape( -1, 4 )
c = np.arange( 1, 7 ).reshape( -1, 2 )

d = np.vstack( (a,b) )
e = np.hstack( (a,c) )

print( "a = ", a, sep="\n" )
print( "*"*40 )
print( "b = ", b, sep="\n" )
print( "*"*40 )
print( "c = ", c, sep="\n" )
print( "*"*40 )

print( "d = ", d, sep="\n" )
print( "*"*40 )

print( "e = ", e, sep="\n" )
print( "*"*40 )


a = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
****************************************
b = 
[[1 2 3 4]
 [5 6 7 8]]
****************************************
c = 
[[1 2]
 [3 4]
 [5 6]]
****************************************
d = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
****************************************
e = 
[[ 1  2  3  4  1  2]
 [ 5  6  7  8  3  4]
 [ 9 10 11 12  5  6]]
****************************************
