In [ ]:
# 화소(행렬 원소) 접근
import numpy as np

# 화소의 반복 접근 비효율 적
def mat_access( mat ): # c style
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            k = mat[i, j] 
            mat[i, j] = k * 2  # 원소 할당
        pass
    pass
pass 

mat1 = np.arange(10).reshape(2, 5) 

print("원소 처리 전: mat1 = ", mat1, sep="\n")
print( "-"*50 )
mat_access(mat1)
print("원소 처리 후: mat1 = ", mat1, sep="\n") 
print( "-"*50 )

mat2 = np.arange(10).reshape(2, 5) 

print()
print()
print("원소 처리 전: mat2 = ", mat2, sep="\n")
print( "-"*50 )

# 효율적인 접근 방법
mat2 = mat2*2
#mat2 *= 2
print("원소 처리 후: mat2 = ", mat2, sep="\n")
print( "-"*50 )

원소 처리 전: mat1 = 
[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------------------------------------
원소 처리 후: mat1 = 
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
--------------------------------------------------


원소 처리 전: mat2 = 
[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------------------------------------
원소 처리 후: mat2 = 
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
--------------------------------------------------
